name: curl
version: 0.0.1
summary: http client
base: core18
description: |
        Http client
confinement: strict
grade: stable

apps:
    curl:
        command: usr/bin/curl
        plugs: [home, network-bind] 

parts:
    curl:
        plugin: nil
        stage-packages: [curl]
